server:
  port: 80

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.25.16.249:6543/db_eams196
      username: sa
      password: tusc@6789#JKL
      max-active: 10                                #最大连接数
      initial-size: 1
      min-idle: 1                                   #最小连接数
      max-wait: 60000                               #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000      #间隔多久进行一次检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000        #一个连接在池中最小生存时间 单位是毫秒
  main:
      allow-bean-definition-overriding: true

mybatis:
  type-aliases-package: cn.lee.databasemanagement.bean